name:                divisors
version:             0.1.0.0
github:              "fimmind/divisors"
license:             BSD3
author:              "Serafim Vinogrodskiy"
maintainer:          "grayfox19@mail.ru"
copyright:           "2019 Serafim Vinogrodskiy"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fimmind/divisors#readme>

dependencies:
- base >= 4.7 && < 5
- primes
- cond

library:
  source-dirs: src

executables:
  divisors-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - divisors

tests:
  divisors-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - divisors
